version: '3.9'
services:
  postgres:
    container_name: postgres-container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jsppass
      POSTGRES_DB: jsp-db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/home/data # local-machine:container-machine

  pgadmin:
    container_name: pgadmin4-container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: jsppass
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./data:/home/data # local-machine:container-machine

volumes:
  data:
