version: '3.9'
services:
  # PostgresSQL service.
  postgres:
    container_name: postgres-container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsp-db
    ports:
      - "5432:5432"
    volumes:
      - ./jsp/datalake:/home/datalake # local-machine:container-process.
