[tool.poetry]
name = "Job Salary Prediction"
version = "0.1.0"
description = "Predict the salary of any UK job ad based on its contents."
authors = ["drigols <drigols.creative@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
notebook = "^6.4.12"
matplotlib = "^3.6.0"
pandas = "^1.5.0"
py7zr = "^0.20.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
