[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

# Ignore flat-layout.
[tool.setuptools]
py-modules = []

[project]
name = "jsp"
version = "4.0.0"
description = "Predict the salary of any UK job ad based on its contents."
license = {file = "LICENSE.md"}
readme = "README.md"
requires-python = ">=3.10.0"
authors = [
    { name = "Rodrigo Leite", email = "drigols.creative@gmail.com" },
]
maintainers = [
    { name = "Rodrigo Leite", email = "drigols.creative@gmail.com" },
]
keywords = [
    "eda",
    "statistics",
    "machine Learning",
]

dependencies = [
    "notebook>=6.5.2",
    "py7zr>=0.20.2",
    "pandas>=1.5.2",
    "scikit-learn>=1.2.0",
    "numpy>=1.23.5",
    "catboost>=1.1.1",
    "ipywidgets>=8.0.3",
]

[project.optional-dependencies]
# Dev dependencies.
dev = [
    "pre-commit>=2.20.0",
    "black>=22.12.0",
    "flake8>=6.0.0",
    "reorder-python-imports>=3.9.0",
    "pyupgrade>=3.3.1",
]
# Test dependencies.
test = []
# Doc dependencies.
doc = []

[tool.black]
line-length = 79
include = '\.pyi?$' # All Python files
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
