[tool.poetry]
name = "job-salary-prediction"
version = "0.1.0"
description = "Predict the salary of any UK job ad based on its contents."
authors = ["drigols <drigols.creative@gmail.com>"]
license = "MIT"
packages = [{ include = "job_salary_prediction" }]
readme = "README.md"
classifiers = [
    "Natural Language :: English",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
taskipy = "^1.12.0"
scikit-learn = "^1.3.0"
catboost = "^1.2"
pandas = "^2.0.3"
black = "^23.7.0"
isort = "^5.12.0"
flake8 = "^6.1.0"
pre-commit = "^3.3.3"
pyupgrade = "^3.10.1"
bandit = "^1.7.5"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--doctest-modules"

[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]
add_future = "isort . --add-import 'from __future__ import annotations'"
lint = "task add_future && black --check --diff . && isort --check --diff . && flake8 ."
security = "bandit ."
precommit = "pre-commit run --all-files"
checkall = "task lint && task security && task precommit"
pre_test = "task lint && task precommit && task security -r"
test = "pytest -s -x --cov=dota2learning -vv"
post_test = "coverage html"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/drigols/job-salary-prediction/issues"

[tool.black]
line-length = 79
include = '\.pyi?$' # All Python files
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
